// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "login.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace login {
class LoginMsgDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<LoginMsg>
     _instance;
  const ::common::TestReq* test_req_;
  const ::common::TestRsp* test_rsp_;
  const ::login::LoginReq* login_req_;
  const ::login::LoginRsp* login_rsp_;
  const ::login::AccessKeyReq* access_key_req_;
  const ::login::AccessKeyRsp* access_key_rsp_;
} _LoginMsg_default_instance_;
class LoginReqDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<LoginReq>
     _instance;
} _LoginReq_default_instance_;
class LoginRspDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<LoginRsp>
     _instance;
} _LoginRsp_default_instance_;
class AccessKeyReqDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<AccessKeyReq>
     _instance;
} _AccessKeyReq_default_instance_;
class AccessKeyRspDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<AccessKeyRsp>
     _instance;
} _AccessKeyRsp_default_instance_;

namespace protobuf_login_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[5];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginMsg, _oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  offsetof(LoginMsgDefaultTypeInternal, test_req_),
  offsetof(LoginMsgDefaultTypeInternal, test_rsp_),
  offsetof(LoginMsgDefaultTypeInternal, login_req_),
  offsetof(LoginMsgDefaultTypeInternal, login_rsp_),
  offsetof(LoginMsgDefaultTypeInternal, access_key_req_),
  offsetof(LoginMsgDefaultTypeInternal, access_key_rsp_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginMsg, choice_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginReq, service_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginReq, proc_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginReq, user_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginReq, passwd_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginReq, dev_type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginReq, dev_token_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginRsp, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AccessKeyReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AccessKeyRsp, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AccessKeyRsp, access_key_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(LoginMsg)},
  { 12, -1, sizeof(LoginReq)},
  { 23, -1, sizeof(LoginRsp)},
  { 28, -1, sizeof(AccessKeyReq)},
  { 33, -1, sizeof(AccessKeyRsp)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_LoginMsg_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_LoginReq_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_LoginRsp_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_AccessKeyReq_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_AccessKeyRsp_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "login.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 5);
}

}  // namespace
void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  ::common::protobuf_common_2eproto::InitDefaults();
  _LoginMsg_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_LoginMsg_default_instance_);_LoginReq_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_LoginReq_default_instance_);_LoginRsp_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_LoginRsp_default_instance_);_AccessKeyReq_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_AccessKeyReq_default_instance_);_AccessKeyRsp_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_AccessKeyRsp_default_instance_);_LoginMsg_default_instance_.test_req_ = const_cast< ::common::TestReq*>(
      ::common::TestReq::internal_default_instance());
  _LoginMsg_default_instance_.test_rsp_ = const_cast< ::common::TestRsp*>(
      ::common::TestRsp::internal_default_instance());
  _LoginMsg_default_instance_.login_req_ = const_cast< ::login::LoginReq*>(
      ::login::LoginReq::internal_default_instance());
  _LoginMsg_default_instance_.login_rsp_ = const_cast< ::login::LoginRsp*>(
      ::login::LoginRsp::internal_default_instance());
  _LoginMsg_default_instance_.access_key_req_ = const_cast< ::login::AccessKeyReq*>(
      ::login::AccessKeyReq::internal_default_instance());
  _LoginMsg_default_instance_.access_key_rsp_ = const_cast< ::login::AccessKeyRsp*>(
      ::login::AccessKeyRsp::internal_default_instance());
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
namespace {
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\013login.proto\022\005login\032\014common.proto\"\210\002\n\010L"
      "oginMsg\022#\n\010test_req\030\001 \001(\0132\017.common.TestR"
      "eqH\000\022#\n\010test_rsp\030\002 \001(\0132\017.common.TestRspH"
      "\000\022$\n\tlogin_req\030\003 \001(\0132\017.login.LoginReqH\000\022"
      "$\n\tlogin_rsp\030\004 \001(\0132\017.login.LoginRspH\000\022-\n"
      "\016access_key_req\030\005 \001(\0132\023.login.AccessKeyR"
      "eqH\000\022-\n\016access_key_rsp\030\006 \001(\0132\023.login.Acc"
      "essKeyRspH\000B\010\n\006choice\"u\n\010LoginReq\022\022\n\nser"
      "vice_id\030\001 \001(\005\022\017\n\007proc_id\030\002 \001(\r\022\017\n\007user_i"
      "d\030\003 \001(\004\022\016\n\006passwd\030\004 \001(\014\022\020\n\010dev_type\030\005 \001("
      "\r\022\021\n\tdev_token\030\006 \001(\014\"\n\n\010LoginRsp\"\016\n\014Acce"
      "ssKeyReq\"\"\n\014AccessKeyRsp\022\022\n\naccess_key\030\001"
      " \001(\014*\330\010\n\tErrorCode\022\013\n\007SUCCESS\020\000\022\024\n\rERR_S"
      "YS_BEGIN\020\244\331\2102\022\027\n\020ERR_SYS_OVERLOAD\020\245\331\2102\022\035"
      "\n\026ERR_SYS_REJECT_SERVICE\020\246\331\2102\022\033\n\024ERR_SYS"
      "_SERVER_INNER\020\247\331\2102\022\026\n\017ERR_SYS_TIMEOUT\020\250\331"
      "\2102\022 \n\031ERR_SYS_NO_INSERVICE_LIST\020\251\331\2102\022\031\n\022"
      "ERR_SYS_TASK_STATE\020\252\331\2102\022\033\n\024ERR_SYS_TASK_"
      "DISCARD\020\253\331\2102\022\022\n\013ERR_SYS_END\020\207\332\2102\022\027\n\020ERR_"
      "PACKET_BEGIN\020\210\332\2102\022\030\n\021ERR_PACKET_ENCODE\020\211"
      "\332\2102\022\030\n\021ERR_PACKET_DECODE\020\212\332\2102\022\030\n\021ERR_PAC"
      "KET_HEADER\020\213\332\2102\022\025\n\016ERR_PACKET_LEN\020\214\332\2102\022\031"
      "\n\022ERR_PACKET_VERSION\020\215\332\2102\022!\n\032ERR_PACKET_"
      "FROM_SERVICE_ID\020\216\332\2102\022\037\n\030ERR_PACKET_TO_SE"
      "RVICE_ID\020\217\332\2102\022\030\n\021ERR_PACKET_APP_ID\020\220\332\2102\022"
      "\035\n\026ERR_PACKET_APP_VERSION\020\221\332\2102\022\035\n\026ERR_PA"
      "CKET_CONN_SEQ_ID\020\222\332\2102\022\034\n\025ERR_PACKET_MSG_"
      "SEQ_ID\020\223\332\2102\022\035\n\026ERR_PACKET_DATA_FORMAT\020\224\332"
      "\2102\022\036\n\027ERR_PACKET_DATA_FIELD_0\020\225\332\2102\022\036\n\027ER"
      "R_PACKET_DATA_FIELD_1\020\226\332\2102\022\036\n\027ERR_PACKET"
      "_DATA_FIELD_2\020\227\332\2102\022\036\n\027ERR_PACKET_DATA_FI"
      "ELD_3\020\230\332\2102\022\033\n\024ERR_PACKET_CHECK_SUM\020\231\332\2102\022"
      "!\n\032ERR_PACKET_UNKNOWN_REQUEST\020\232\332\2102\022\025\n\016ER"
      "R_PACKET_END\020\353\332\2102\022\032\n\023ERR_INTERFACE_BEGIN"
      "\020\354\332\2102\022\032\n\023ERR_INTERFACE_PARAM\020\355\332\2102\022\031\n\022ERR"
      "_INTERFACE_PERM\020\356\332\2102\022\034\n\025ERR_INTERFACE_TI"
      "MEOUT\020\357\332\2102\022#\n\034ERR_INTERFACE_MASTER_TIMEO"
      "UT\020\360\332\2102\022 \n\031ERR_INTERFACE_SUB_TIMEOUT\020\361\332\210"
      "2\022\030\n\021ERR_INTERFACE_END\020\317\333\2102\022\031\n\022ERR_BUSIN"
      "ESS_BEGIN\020\250\340\2102\022\027\n\020ERR_BUSINESS_END\020\317\246\2112b"
      "\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 1607);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "login.proto", &protobuf_RegisterTypes);
  ::common::protobuf_common_2eproto::AddDescriptors();
}
} // anonymous namespace

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_login_2eproto

const ::google::protobuf::EnumDescriptor* ErrorCode_descriptor() {
  protobuf_login_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_login_2eproto::file_level_enum_descriptors[0];
}
bool ErrorCode_IsValid(int value) {
  switch (value) {
    case 0:
    case 105000100:
    case 105000101:
    case 105000102:
    case 105000103:
    case 105000104:
    case 105000105:
    case 105000106:
    case 105000107:
    case 105000199:
    case 105000200:
    case 105000201:
    case 105000202:
    case 105000203:
    case 105000204:
    case 105000205:
    case 105000206:
    case 105000207:
    case 105000208:
    case 105000209:
    case 105000210:
    case 105000211:
    case 105000212:
    case 105000213:
    case 105000214:
    case 105000215:
    case 105000216:
    case 105000217:
    case 105000218:
    case 105000299:
    case 105000300:
    case 105000301:
    case 105000302:
    case 105000303:
    case 105000304:
    case 105000305:
    case 105000399:
    case 105001000:
    case 105009999:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int LoginMsg::kTestReqFieldNumber;
const int LoginMsg::kTestRspFieldNumber;
const int LoginMsg::kLoginReqFieldNumber;
const int LoginMsg::kLoginRspFieldNumber;
const int LoginMsg::kAccessKeyReqFieldNumber;
const int LoginMsg::kAccessKeyRspFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

LoginMsg::LoginMsg()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_login_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:login.LoginMsg)
}
LoginMsg::LoginMsg(const LoginMsg& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  clear_has_choice();
  switch (from.choice_case()) {
    case kTestReq: {
      mutable_test_req()->::common::TestReq::MergeFrom(from.test_req());
      break;
    }
    case kTestRsp: {
      mutable_test_rsp()->::common::TestRsp::MergeFrom(from.test_rsp());
      break;
    }
    case kLoginReq: {
      mutable_login_req()->::login::LoginReq::MergeFrom(from.login_req());
      break;
    }
    case kLoginRsp: {
      mutable_login_rsp()->::login::LoginRsp::MergeFrom(from.login_rsp());
      break;
    }
    case kAccessKeyReq: {
      mutable_access_key_req()->::login::AccessKeyReq::MergeFrom(from.access_key_req());
      break;
    }
    case kAccessKeyRsp: {
      mutable_access_key_rsp()->::login::AccessKeyRsp::MergeFrom(from.access_key_rsp());
      break;
    }
    case CHOICE_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:login.LoginMsg)
}

void LoginMsg::SharedCtor() {
  clear_has_choice();
  _cached_size_ = 0;
}

LoginMsg::~LoginMsg() {
  // @@protoc_insertion_point(destructor:login.LoginMsg)
  SharedDtor();
}

void LoginMsg::SharedDtor() {
  if (has_choice()) {
    clear_choice();
  }
}

void LoginMsg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* LoginMsg::descriptor() {
  protobuf_login_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_login_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const LoginMsg& LoginMsg::default_instance() {
  protobuf_login_2eproto::InitDefaults();
  return *internal_default_instance();
}

LoginMsg* LoginMsg::New(::google::protobuf::Arena* arena) const {
  LoginMsg* n = new LoginMsg;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void LoginMsg::clear_choice() {
// @@protoc_insertion_point(one_of_clear_start:login.LoginMsg)
  switch (choice_case()) {
    case kTestReq: {
      delete choice_.test_req_;
      break;
    }
    case kTestRsp: {
      delete choice_.test_rsp_;
      break;
    }
    case kLoginReq: {
      delete choice_.login_req_;
      break;
    }
    case kLoginRsp: {
      delete choice_.login_rsp_;
      break;
    }
    case kAccessKeyReq: {
      delete choice_.access_key_req_;
      break;
    }
    case kAccessKeyRsp: {
      delete choice_.access_key_rsp_;
      break;
    }
    case CHOICE_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = CHOICE_NOT_SET;
}


void LoginMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:login.LoginMsg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_choice();
  _internal_metadata_.Clear();
}

bool LoginMsg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:login.LoginMsg)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .common.TestReq test_req = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_test_req()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .common.TestRsp test_rsp = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_test_rsp()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .login.LoginReq login_req = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_login_req()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .login.LoginRsp login_rsp = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_login_rsp()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .login.AccessKeyReq access_key_req = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_access_key_req()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .login.AccessKeyRsp access_key_rsp = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_access_key_rsp()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:login.LoginMsg)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:login.LoginMsg)
  return false;
#undef DO_
}

void LoginMsg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:login.LoginMsg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .common.TestReq test_req = 1;
  if (has_test_req()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *choice_.test_req_, output);
  }

  // .common.TestRsp test_rsp = 2;
  if (has_test_rsp()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *choice_.test_rsp_, output);
  }

  // .login.LoginReq login_req = 3;
  if (has_login_req()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, *choice_.login_req_, output);
  }

  // .login.LoginRsp login_rsp = 4;
  if (has_login_rsp()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, *choice_.login_rsp_, output);
  }

  // .login.AccessKeyReq access_key_req = 5;
  if (has_access_key_req()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, *choice_.access_key_req_, output);
  }

  // .login.AccessKeyRsp access_key_rsp = 6;
  if (has_access_key_rsp()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6, *choice_.access_key_rsp_, output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:login.LoginMsg)
}

::google::protobuf::uint8* LoginMsg::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:login.LoginMsg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .common.TestReq test_req = 1;
  if (has_test_req()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *choice_.test_req_, deterministic, target);
  }

  // .common.TestRsp test_rsp = 2;
  if (has_test_rsp()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, *choice_.test_rsp_, deterministic, target);
  }

  // .login.LoginReq login_req = 3;
  if (has_login_req()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        3, *choice_.login_req_, deterministic, target);
  }

  // .login.LoginRsp login_rsp = 4;
  if (has_login_rsp()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        4, *choice_.login_rsp_, deterministic, target);
  }

  // .login.AccessKeyReq access_key_req = 5;
  if (has_access_key_req()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        5, *choice_.access_key_req_, deterministic, target);
  }

  // .login.AccessKeyRsp access_key_rsp = 6;
  if (has_access_key_rsp()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        6, *choice_.access_key_rsp_, deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:login.LoginMsg)
  return target;
}

size_t LoginMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:login.LoginMsg)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  switch (choice_case()) {
    // .common.TestReq test_req = 1;
    case kTestReq: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *choice_.test_req_);
      break;
    }
    // .common.TestRsp test_rsp = 2;
    case kTestRsp: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *choice_.test_rsp_);
      break;
    }
    // .login.LoginReq login_req = 3;
    case kLoginReq: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *choice_.login_req_);
      break;
    }
    // .login.LoginRsp login_rsp = 4;
    case kLoginRsp: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *choice_.login_rsp_);
      break;
    }
    // .login.AccessKeyReq access_key_req = 5;
    case kAccessKeyReq: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *choice_.access_key_req_);
      break;
    }
    // .login.AccessKeyRsp access_key_rsp = 6;
    case kAccessKeyRsp: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *choice_.access_key_rsp_);
      break;
    }
    case CHOICE_NOT_SET: {
      break;
    }
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void LoginMsg::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:login.LoginMsg)
  GOOGLE_DCHECK_NE(&from, this);
  const LoginMsg* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const LoginMsg>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:login.LoginMsg)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:login.LoginMsg)
    MergeFrom(*source);
  }
}

void LoginMsg::MergeFrom(const LoginMsg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:login.LoginMsg)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  switch (from.choice_case()) {
    case kTestReq: {
      mutable_test_req()->::common::TestReq::MergeFrom(from.test_req());
      break;
    }
    case kTestRsp: {
      mutable_test_rsp()->::common::TestRsp::MergeFrom(from.test_rsp());
      break;
    }
    case kLoginReq: {
      mutable_login_req()->::login::LoginReq::MergeFrom(from.login_req());
      break;
    }
    case kLoginRsp: {
      mutable_login_rsp()->::login::LoginRsp::MergeFrom(from.login_rsp());
      break;
    }
    case kAccessKeyReq: {
      mutable_access_key_req()->::login::AccessKeyReq::MergeFrom(from.access_key_req());
      break;
    }
    case kAccessKeyRsp: {
      mutable_access_key_rsp()->::login::AccessKeyRsp::MergeFrom(from.access_key_rsp());
      break;
    }
    case CHOICE_NOT_SET: {
      break;
    }
  }
}

void LoginMsg::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:login.LoginMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LoginMsg::CopyFrom(const LoginMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:login.LoginMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LoginMsg::IsInitialized() const {
  return true;
}

void LoginMsg::Swap(LoginMsg* other) {
  if (other == this) return;
  InternalSwap(other);
}
void LoginMsg::InternalSwap(LoginMsg* other) {
  using std::swap;
  swap(choice_, other->choice_);
  swap(_oneof_case_[0], other->_oneof_case_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata LoginMsg::GetMetadata() const {
  protobuf_login_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_login_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// LoginMsg

// .common.TestReq test_req = 1;
bool LoginMsg::has_test_req() const {
  return choice_case() == kTestReq;
}
void LoginMsg::set_has_test_req() {
  _oneof_case_[0] = kTestReq;
}
void LoginMsg::clear_test_req() {
  if (has_test_req()) {
    delete choice_.test_req_;
    clear_has_choice();
  }
}
 const ::common::TestReq& LoginMsg::test_req() const {
  // @@protoc_insertion_point(field_get:login.LoginMsg.test_req)
  return has_test_req()
      ? *choice_.test_req_
      : ::common::TestReq::default_instance();
}
::common::TestReq* LoginMsg::mutable_test_req() {
  if (!has_test_req()) {
    clear_choice();
    set_has_test_req();
    choice_.test_req_ = new ::common::TestReq;
  }
  // @@protoc_insertion_point(field_mutable:login.LoginMsg.test_req)
  return choice_.test_req_;
}
::common::TestReq* LoginMsg::release_test_req() {
  // @@protoc_insertion_point(field_release:login.LoginMsg.test_req)
  if (has_test_req()) {
    clear_has_choice();
    ::common::TestReq* temp = choice_.test_req_;
    choice_.test_req_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
void LoginMsg::set_allocated_test_req(::common::TestReq* test_req) {
  clear_choice();
  if (test_req) {
    set_has_test_req();
    choice_.test_req_ = test_req;
  }
  // @@protoc_insertion_point(field_set_allocated:login.LoginMsg.test_req)
}

// .common.TestRsp test_rsp = 2;
bool LoginMsg::has_test_rsp() const {
  return choice_case() == kTestRsp;
}
void LoginMsg::set_has_test_rsp() {
  _oneof_case_[0] = kTestRsp;
}
void LoginMsg::clear_test_rsp() {
  if (has_test_rsp()) {
    delete choice_.test_rsp_;
    clear_has_choice();
  }
}
 const ::common::TestRsp& LoginMsg::test_rsp() const {
  // @@protoc_insertion_point(field_get:login.LoginMsg.test_rsp)
  return has_test_rsp()
      ? *choice_.test_rsp_
      : ::common::TestRsp::default_instance();
}
::common::TestRsp* LoginMsg::mutable_test_rsp() {
  if (!has_test_rsp()) {
    clear_choice();
    set_has_test_rsp();
    choice_.test_rsp_ = new ::common::TestRsp;
  }
  // @@protoc_insertion_point(field_mutable:login.LoginMsg.test_rsp)
  return choice_.test_rsp_;
}
::common::TestRsp* LoginMsg::release_test_rsp() {
  // @@protoc_insertion_point(field_release:login.LoginMsg.test_rsp)
  if (has_test_rsp()) {
    clear_has_choice();
    ::common::TestRsp* temp = choice_.test_rsp_;
    choice_.test_rsp_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
void LoginMsg::set_allocated_test_rsp(::common::TestRsp* test_rsp) {
  clear_choice();
  if (test_rsp) {
    set_has_test_rsp();
    choice_.test_rsp_ = test_rsp;
  }
  // @@protoc_insertion_point(field_set_allocated:login.LoginMsg.test_rsp)
}

// .login.LoginReq login_req = 3;
bool LoginMsg::has_login_req() const {
  return choice_case() == kLoginReq;
}
void LoginMsg::set_has_login_req() {
  _oneof_case_[0] = kLoginReq;
}
void LoginMsg::clear_login_req() {
  if (has_login_req()) {
    delete choice_.login_req_;
    clear_has_choice();
  }
}
 const ::login::LoginReq& LoginMsg::login_req() const {
  // @@protoc_insertion_point(field_get:login.LoginMsg.login_req)
  return has_login_req()
      ? *choice_.login_req_
      : ::login::LoginReq::default_instance();
}
::login::LoginReq* LoginMsg::mutable_login_req() {
  if (!has_login_req()) {
    clear_choice();
    set_has_login_req();
    choice_.login_req_ = new ::login::LoginReq;
  }
  // @@protoc_insertion_point(field_mutable:login.LoginMsg.login_req)
  return choice_.login_req_;
}
::login::LoginReq* LoginMsg::release_login_req() {
  // @@protoc_insertion_point(field_release:login.LoginMsg.login_req)
  if (has_login_req()) {
    clear_has_choice();
    ::login::LoginReq* temp = choice_.login_req_;
    choice_.login_req_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
void LoginMsg::set_allocated_login_req(::login::LoginReq* login_req) {
  clear_choice();
  if (login_req) {
    set_has_login_req();
    choice_.login_req_ = login_req;
  }
  // @@protoc_insertion_point(field_set_allocated:login.LoginMsg.login_req)
}

// .login.LoginRsp login_rsp = 4;
bool LoginMsg::has_login_rsp() const {
  return choice_case() == kLoginRsp;
}
void LoginMsg::set_has_login_rsp() {
  _oneof_case_[0] = kLoginRsp;
}
void LoginMsg::clear_login_rsp() {
  if (has_login_rsp()) {
    delete choice_.login_rsp_;
    clear_has_choice();
  }
}
 const ::login::LoginRsp& LoginMsg::login_rsp() const {
  // @@protoc_insertion_point(field_get:login.LoginMsg.login_rsp)
  return has_login_rsp()
      ? *choice_.login_rsp_
      : ::login::LoginRsp::default_instance();
}
::login::LoginRsp* LoginMsg::mutable_login_rsp() {
  if (!has_login_rsp()) {
    clear_choice();
    set_has_login_rsp();
    choice_.login_rsp_ = new ::login::LoginRsp;
  }
  // @@protoc_insertion_point(field_mutable:login.LoginMsg.login_rsp)
  return choice_.login_rsp_;
}
::login::LoginRsp* LoginMsg::release_login_rsp() {
  // @@protoc_insertion_point(field_release:login.LoginMsg.login_rsp)
  if (has_login_rsp()) {
    clear_has_choice();
    ::login::LoginRsp* temp = choice_.login_rsp_;
    choice_.login_rsp_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
void LoginMsg::set_allocated_login_rsp(::login::LoginRsp* login_rsp) {
  clear_choice();
  if (login_rsp) {
    set_has_login_rsp();
    choice_.login_rsp_ = login_rsp;
  }
  // @@protoc_insertion_point(field_set_allocated:login.LoginMsg.login_rsp)
}

// .login.AccessKeyReq access_key_req = 5;
bool LoginMsg::has_access_key_req() const {
  return choice_case() == kAccessKeyReq;
}
void LoginMsg::set_has_access_key_req() {
  _oneof_case_[0] = kAccessKeyReq;
}
void LoginMsg::clear_access_key_req() {
  if (has_access_key_req()) {
    delete choice_.access_key_req_;
    clear_has_choice();
  }
}
 const ::login::AccessKeyReq& LoginMsg::access_key_req() const {
  // @@protoc_insertion_point(field_get:login.LoginMsg.access_key_req)
  return has_access_key_req()
      ? *choice_.access_key_req_
      : ::login::AccessKeyReq::default_instance();
}
::login::AccessKeyReq* LoginMsg::mutable_access_key_req() {
  if (!has_access_key_req()) {
    clear_choice();
    set_has_access_key_req();
    choice_.access_key_req_ = new ::login::AccessKeyReq;
  }
  // @@protoc_insertion_point(field_mutable:login.LoginMsg.access_key_req)
  return choice_.access_key_req_;
}
::login::AccessKeyReq* LoginMsg::release_access_key_req() {
  // @@protoc_insertion_point(field_release:login.LoginMsg.access_key_req)
  if (has_access_key_req()) {
    clear_has_choice();
    ::login::AccessKeyReq* temp = choice_.access_key_req_;
    choice_.access_key_req_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
void LoginMsg::set_allocated_access_key_req(::login::AccessKeyReq* access_key_req) {
  clear_choice();
  if (access_key_req) {
    set_has_access_key_req();
    choice_.access_key_req_ = access_key_req;
  }
  // @@protoc_insertion_point(field_set_allocated:login.LoginMsg.access_key_req)
}

// .login.AccessKeyRsp access_key_rsp = 6;
bool LoginMsg::has_access_key_rsp() const {
  return choice_case() == kAccessKeyRsp;
}
void LoginMsg::set_has_access_key_rsp() {
  _oneof_case_[0] = kAccessKeyRsp;
}
void LoginMsg::clear_access_key_rsp() {
  if (has_access_key_rsp()) {
    delete choice_.access_key_rsp_;
    clear_has_choice();
  }
}
 const ::login::AccessKeyRsp& LoginMsg::access_key_rsp() const {
  // @@protoc_insertion_point(field_get:login.LoginMsg.access_key_rsp)
  return has_access_key_rsp()
      ? *choice_.access_key_rsp_
      : ::login::AccessKeyRsp::default_instance();
}
::login::AccessKeyRsp* LoginMsg::mutable_access_key_rsp() {
  if (!has_access_key_rsp()) {
    clear_choice();
    set_has_access_key_rsp();
    choice_.access_key_rsp_ = new ::login::AccessKeyRsp;
  }
  // @@protoc_insertion_point(field_mutable:login.LoginMsg.access_key_rsp)
  return choice_.access_key_rsp_;
}
::login::AccessKeyRsp* LoginMsg::release_access_key_rsp() {
  // @@protoc_insertion_point(field_release:login.LoginMsg.access_key_rsp)
  if (has_access_key_rsp()) {
    clear_has_choice();
    ::login::AccessKeyRsp* temp = choice_.access_key_rsp_;
    choice_.access_key_rsp_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
void LoginMsg::set_allocated_access_key_rsp(::login::AccessKeyRsp* access_key_rsp) {
  clear_choice();
  if (access_key_rsp) {
    set_has_access_key_rsp();
    choice_.access_key_rsp_ = access_key_rsp;
  }
  // @@protoc_insertion_point(field_set_allocated:login.LoginMsg.access_key_rsp)
}

bool LoginMsg::has_choice() const {
  return choice_case() != CHOICE_NOT_SET;
}
void LoginMsg::clear_has_choice() {
  _oneof_case_[0] = CHOICE_NOT_SET;
}
LoginMsg::ChoiceCase LoginMsg::choice_case() const {
  return LoginMsg::ChoiceCase(_oneof_case_[0]);
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int LoginReq::kServiceIdFieldNumber;
const int LoginReq::kProcIdFieldNumber;
const int LoginReq::kUserIdFieldNumber;
const int LoginReq::kPasswdFieldNumber;
const int LoginReq::kDevTypeFieldNumber;
const int LoginReq::kDevTokenFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

LoginReq::LoginReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_login_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:login.LoginReq)
}
LoginReq::LoginReq(const LoginReq& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  passwd_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.passwd().size() > 0) {
    passwd_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.passwd_);
  }
  dev_token_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.dev_token().size() > 0) {
    dev_token_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.dev_token_);
  }
  ::memcpy(&service_id_, &from.service_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&dev_type_) -
    reinterpret_cast<char*>(&service_id_)) + sizeof(dev_type_));
  // @@protoc_insertion_point(copy_constructor:login.LoginReq)
}

void LoginReq::SharedCtor() {
  passwd_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  dev_token_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&service_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&dev_type_) -
      reinterpret_cast<char*>(&service_id_)) + sizeof(dev_type_));
  _cached_size_ = 0;
}

LoginReq::~LoginReq() {
  // @@protoc_insertion_point(destructor:login.LoginReq)
  SharedDtor();
}

void LoginReq::SharedDtor() {
  passwd_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  dev_token_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void LoginReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* LoginReq::descriptor() {
  protobuf_login_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_login_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const LoginReq& LoginReq::default_instance() {
  protobuf_login_2eproto::InitDefaults();
  return *internal_default_instance();
}

LoginReq* LoginReq::New(::google::protobuf::Arena* arena) const {
  LoginReq* n = new LoginReq;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void LoginReq::Clear() {
// @@protoc_insertion_point(message_clear_start:login.LoginReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  passwd_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  dev_token_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&service_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&dev_type_) -
      reinterpret_cast<char*>(&service_id_)) + sizeof(dev_type_));
  _internal_metadata_.Clear();
}

bool LoginReq::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:login.LoginReq)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 service_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &service_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 proc_id = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &proc_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 user_id = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &user_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes passwd = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_passwd()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 dev_type = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &dev_type_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes dev_token = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_dev_token()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:login.LoginReq)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:login.LoginReq)
  return false;
#undef DO_
}

void LoginReq::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:login.LoginReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 service_id = 1;
  if (this->service_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->service_id(), output);
  }

  // uint32 proc_id = 2;
  if (this->proc_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->proc_id(), output);
  }

  // uint64 user_id = 3;
  if (this->user_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(3, this->user_id(), output);
  }

  // bytes passwd = 4;
  if (this->passwd().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      4, this->passwd(), output);
  }

  // uint32 dev_type = 5;
  if (this->dev_type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(5, this->dev_type(), output);
  }

  // bytes dev_token = 6;
  if (this->dev_token().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      6, this->dev_token(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:login.LoginReq)
}

::google::protobuf::uint8* LoginReq::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:login.LoginReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 service_id = 1;
  if (this->service_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->service_id(), target);
  }

  // uint32 proc_id = 2;
  if (this->proc_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->proc_id(), target);
  }

  // uint64 user_id = 3;
  if (this->user_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(3, this->user_id(), target);
  }

  // bytes passwd = 4;
  if (this->passwd().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        4, this->passwd(), target);
  }

  // uint32 dev_type = 5;
  if (this->dev_type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(5, this->dev_type(), target);
  }

  // bytes dev_token = 6;
  if (this->dev_token().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        6, this->dev_token(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:login.LoginReq)
  return target;
}

size_t LoginReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:login.LoginReq)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // bytes passwd = 4;
  if (this->passwd().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->passwd());
  }

  // bytes dev_token = 6;
  if (this->dev_token().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->dev_token());
  }

  // int32 service_id = 1;
  if (this->service_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->service_id());
  }

  // uint32 proc_id = 2;
  if (this->proc_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->proc_id());
  }

  // uint64 user_id = 3;
  if (this->user_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->user_id());
  }

  // uint32 dev_type = 5;
  if (this->dev_type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->dev_type());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void LoginReq::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:login.LoginReq)
  GOOGLE_DCHECK_NE(&from, this);
  const LoginReq* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const LoginReq>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:login.LoginReq)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:login.LoginReq)
    MergeFrom(*source);
  }
}

void LoginReq::MergeFrom(const LoginReq& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:login.LoginReq)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.passwd().size() > 0) {

    passwd_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.passwd_);
  }
  if (from.dev_token().size() > 0) {

    dev_token_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.dev_token_);
  }
  if (from.service_id() != 0) {
    set_service_id(from.service_id());
  }
  if (from.proc_id() != 0) {
    set_proc_id(from.proc_id());
  }
  if (from.user_id() != 0) {
    set_user_id(from.user_id());
  }
  if (from.dev_type() != 0) {
    set_dev_type(from.dev_type());
  }
}

void LoginReq::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:login.LoginReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LoginReq::CopyFrom(const LoginReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:login.LoginReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LoginReq::IsInitialized() const {
  return true;
}

void LoginReq::Swap(LoginReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void LoginReq::InternalSwap(LoginReq* other) {
  using std::swap;
  passwd_.Swap(&other->passwd_);
  dev_token_.Swap(&other->dev_token_);
  swap(service_id_, other->service_id_);
  swap(proc_id_, other->proc_id_);
  swap(user_id_, other->user_id_);
  swap(dev_type_, other->dev_type_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata LoginReq::GetMetadata() const {
  protobuf_login_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_login_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// LoginReq

// int32 service_id = 1;
void LoginReq::clear_service_id() {
  service_id_ = 0;
}
::google::protobuf::int32 LoginReq::service_id() const {
  // @@protoc_insertion_point(field_get:login.LoginReq.service_id)
  return service_id_;
}
void LoginReq::set_service_id(::google::protobuf::int32 value) {
  
  service_id_ = value;
  // @@protoc_insertion_point(field_set:login.LoginReq.service_id)
}

// uint32 proc_id = 2;
void LoginReq::clear_proc_id() {
  proc_id_ = 0u;
}
::google::protobuf::uint32 LoginReq::proc_id() const {
  // @@protoc_insertion_point(field_get:login.LoginReq.proc_id)
  return proc_id_;
}
void LoginReq::set_proc_id(::google::protobuf::uint32 value) {
  
  proc_id_ = value;
  // @@protoc_insertion_point(field_set:login.LoginReq.proc_id)
}

// uint64 user_id = 3;
void LoginReq::clear_user_id() {
  user_id_ = GOOGLE_ULONGLONG(0);
}
::google::protobuf::uint64 LoginReq::user_id() const {
  // @@protoc_insertion_point(field_get:login.LoginReq.user_id)
  return user_id_;
}
void LoginReq::set_user_id(::google::protobuf::uint64 value) {
  
  user_id_ = value;
  // @@protoc_insertion_point(field_set:login.LoginReq.user_id)
}

// bytes passwd = 4;
void LoginReq::clear_passwd() {
  passwd_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& LoginReq::passwd() const {
  // @@protoc_insertion_point(field_get:login.LoginReq.passwd)
  return passwd_.GetNoArena();
}
void LoginReq::set_passwd(const ::std::string& value) {
  
  passwd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:login.LoginReq.passwd)
}
#if LANG_CXX11
void LoginReq::set_passwd(::std::string&& value) {
  
  passwd_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:login.LoginReq.passwd)
}
#endif
void LoginReq::set_passwd(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  passwd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:login.LoginReq.passwd)
}
void LoginReq::set_passwd(const void* value, size_t size) {
  
  passwd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:login.LoginReq.passwd)
}
::std::string* LoginReq::mutable_passwd() {
  
  // @@protoc_insertion_point(field_mutable:login.LoginReq.passwd)
  return passwd_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* LoginReq::release_passwd() {
  // @@protoc_insertion_point(field_release:login.LoginReq.passwd)
  
  return passwd_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void LoginReq::set_allocated_passwd(::std::string* passwd) {
  if (passwd != NULL) {
    
  } else {
    
  }
  passwd_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), passwd);
  // @@protoc_insertion_point(field_set_allocated:login.LoginReq.passwd)
}

// uint32 dev_type = 5;
void LoginReq::clear_dev_type() {
  dev_type_ = 0u;
}
::google::protobuf::uint32 LoginReq::dev_type() const {
  // @@protoc_insertion_point(field_get:login.LoginReq.dev_type)
  return dev_type_;
}
void LoginReq::set_dev_type(::google::protobuf::uint32 value) {
  
  dev_type_ = value;
  // @@protoc_insertion_point(field_set:login.LoginReq.dev_type)
}

// bytes dev_token = 6;
void LoginReq::clear_dev_token() {
  dev_token_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& LoginReq::dev_token() const {
  // @@protoc_insertion_point(field_get:login.LoginReq.dev_token)
  return dev_token_.GetNoArena();
}
void LoginReq::set_dev_token(const ::std::string& value) {
  
  dev_token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:login.LoginReq.dev_token)
}
#if LANG_CXX11
void LoginReq::set_dev_token(::std::string&& value) {
  
  dev_token_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:login.LoginReq.dev_token)
}
#endif
void LoginReq::set_dev_token(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  dev_token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:login.LoginReq.dev_token)
}
void LoginReq::set_dev_token(const void* value, size_t size) {
  
  dev_token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:login.LoginReq.dev_token)
}
::std::string* LoginReq::mutable_dev_token() {
  
  // @@protoc_insertion_point(field_mutable:login.LoginReq.dev_token)
  return dev_token_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* LoginReq::release_dev_token() {
  // @@protoc_insertion_point(field_release:login.LoginReq.dev_token)
  
  return dev_token_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void LoginReq::set_allocated_dev_token(::std::string* dev_token) {
  if (dev_token != NULL) {
    
  } else {
    
  }
  dev_token_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), dev_token);
  // @@protoc_insertion_point(field_set_allocated:login.LoginReq.dev_token)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

LoginRsp::LoginRsp()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_login_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:login.LoginRsp)
}
LoginRsp::LoginRsp(const LoginRsp& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:login.LoginRsp)
}

void LoginRsp::SharedCtor() {
  _cached_size_ = 0;
}

LoginRsp::~LoginRsp() {
  // @@protoc_insertion_point(destructor:login.LoginRsp)
  SharedDtor();
}

void LoginRsp::SharedDtor() {
}

void LoginRsp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* LoginRsp::descriptor() {
  protobuf_login_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_login_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const LoginRsp& LoginRsp::default_instance() {
  protobuf_login_2eproto::InitDefaults();
  return *internal_default_instance();
}

LoginRsp* LoginRsp::New(::google::protobuf::Arena* arena) const {
  LoginRsp* n = new LoginRsp;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void LoginRsp::Clear() {
// @@protoc_insertion_point(message_clear_start:login.LoginRsp)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

bool LoginRsp::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:login.LoginRsp)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:login.LoginRsp)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:login.LoginRsp)
  return false;
#undef DO_
}

void LoginRsp::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:login.LoginRsp)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:login.LoginRsp)
}

::google::protobuf::uint8* LoginRsp::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:login.LoginRsp)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:login.LoginRsp)
  return target;
}

size_t LoginRsp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:login.LoginRsp)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void LoginRsp::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:login.LoginRsp)
  GOOGLE_DCHECK_NE(&from, this);
  const LoginRsp* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const LoginRsp>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:login.LoginRsp)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:login.LoginRsp)
    MergeFrom(*source);
  }
}

void LoginRsp::MergeFrom(const LoginRsp& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:login.LoginRsp)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void LoginRsp::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:login.LoginRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LoginRsp::CopyFrom(const LoginRsp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:login.LoginRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LoginRsp::IsInitialized() const {
  return true;
}

void LoginRsp::Swap(LoginRsp* other) {
  if (other == this) return;
  InternalSwap(other);
}
void LoginRsp::InternalSwap(LoginRsp* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata LoginRsp::GetMetadata() const {
  protobuf_login_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_login_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// LoginRsp

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

AccessKeyReq::AccessKeyReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_login_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:login.AccessKeyReq)
}
AccessKeyReq::AccessKeyReq(const AccessKeyReq& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:login.AccessKeyReq)
}

void AccessKeyReq::SharedCtor() {
  _cached_size_ = 0;
}

AccessKeyReq::~AccessKeyReq() {
  // @@protoc_insertion_point(destructor:login.AccessKeyReq)
  SharedDtor();
}

void AccessKeyReq::SharedDtor() {
}

void AccessKeyReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* AccessKeyReq::descriptor() {
  protobuf_login_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_login_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const AccessKeyReq& AccessKeyReq::default_instance() {
  protobuf_login_2eproto::InitDefaults();
  return *internal_default_instance();
}

AccessKeyReq* AccessKeyReq::New(::google::protobuf::Arena* arena) const {
  AccessKeyReq* n = new AccessKeyReq;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void AccessKeyReq::Clear() {
// @@protoc_insertion_point(message_clear_start:login.AccessKeyReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

bool AccessKeyReq::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:login.AccessKeyReq)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:login.AccessKeyReq)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:login.AccessKeyReq)
  return false;
#undef DO_
}

void AccessKeyReq::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:login.AccessKeyReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:login.AccessKeyReq)
}

::google::protobuf::uint8* AccessKeyReq::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:login.AccessKeyReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:login.AccessKeyReq)
  return target;
}

size_t AccessKeyReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:login.AccessKeyReq)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void AccessKeyReq::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:login.AccessKeyReq)
  GOOGLE_DCHECK_NE(&from, this);
  const AccessKeyReq* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const AccessKeyReq>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:login.AccessKeyReq)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:login.AccessKeyReq)
    MergeFrom(*source);
  }
}

void AccessKeyReq::MergeFrom(const AccessKeyReq& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:login.AccessKeyReq)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void AccessKeyReq::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:login.AccessKeyReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AccessKeyReq::CopyFrom(const AccessKeyReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:login.AccessKeyReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AccessKeyReq::IsInitialized() const {
  return true;
}

void AccessKeyReq::Swap(AccessKeyReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void AccessKeyReq::InternalSwap(AccessKeyReq* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata AccessKeyReq::GetMetadata() const {
  protobuf_login_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_login_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// AccessKeyReq

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int AccessKeyRsp::kAccessKeyFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

AccessKeyRsp::AccessKeyRsp()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_login_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:login.AccessKeyRsp)
}
AccessKeyRsp::AccessKeyRsp(const AccessKeyRsp& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  access_key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.access_key().size() > 0) {
    access_key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.access_key_);
  }
  // @@protoc_insertion_point(copy_constructor:login.AccessKeyRsp)
}

void AccessKeyRsp::SharedCtor() {
  access_key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

AccessKeyRsp::~AccessKeyRsp() {
  // @@protoc_insertion_point(destructor:login.AccessKeyRsp)
  SharedDtor();
}

void AccessKeyRsp::SharedDtor() {
  access_key_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void AccessKeyRsp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* AccessKeyRsp::descriptor() {
  protobuf_login_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_login_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const AccessKeyRsp& AccessKeyRsp::default_instance() {
  protobuf_login_2eproto::InitDefaults();
  return *internal_default_instance();
}

AccessKeyRsp* AccessKeyRsp::New(::google::protobuf::Arena* arena) const {
  AccessKeyRsp* n = new AccessKeyRsp;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void AccessKeyRsp::Clear() {
// @@protoc_insertion_point(message_clear_start:login.AccessKeyRsp)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  access_key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool AccessKeyRsp::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:login.AccessKeyRsp)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bytes access_key = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_access_key()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:login.AccessKeyRsp)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:login.AccessKeyRsp)
  return false;
#undef DO_
}

void AccessKeyRsp::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:login.AccessKeyRsp)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes access_key = 1;
  if (this->access_key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->access_key(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:login.AccessKeyRsp)
}

::google::protobuf::uint8* AccessKeyRsp::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:login.AccessKeyRsp)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes access_key = 1;
  if (this->access_key().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->access_key(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:login.AccessKeyRsp)
  return target;
}

size_t AccessKeyRsp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:login.AccessKeyRsp)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // bytes access_key = 1;
  if (this->access_key().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->access_key());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void AccessKeyRsp::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:login.AccessKeyRsp)
  GOOGLE_DCHECK_NE(&from, this);
  const AccessKeyRsp* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const AccessKeyRsp>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:login.AccessKeyRsp)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:login.AccessKeyRsp)
    MergeFrom(*source);
  }
}

void AccessKeyRsp::MergeFrom(const AccessKeyRsp& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:login.AccessKeyRsp)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.access_key().size() > 0) {

    access_key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.access_key_);
  }
}

void AccessKeyRsp::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:login.AccessKeyRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AccessKeyRsp::CopyFrom(const AccessKeyRsp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:login.AccessKeyRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AccessKeyRsp::IsInitialized() const {
  return true;
}

void AccessKeyRsp::Swap(AccessKeyRsp* other) {
  if (other == this) return;
  InternalSwap(other);
}
void AccessKeyRsp::InternalSwap(AccessKeyRsp* other) {
  using std::swap;
  access_key_.Swap(&other->access_key_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata AccessKeyRsp::GetMetadata() const {
  protobuf_login_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_login_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// AccessKeyRsp

// bytes access_key = 1;
void AccessKeyRsp::clear_access_key() {
  access_key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& AccessKeyRsp::access_key() const {
  // @@protoc_insertion_point(field_get:login.AccessKeyRsp.access_key)
  return access_key_.GetNoArena();
}
void AccessKeyRsp::set_access_key(const ::std::string& value) {
  
  access_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:login.AccessKeyRsp.access_key)
}
#if LANG_CXX11
void AccessKeyRsp::set_access_key(::std::string&& value) {
  
  access_key_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:login.AccessKeyRsp.access_key)
}
#endif
void AccessKeyRsp::set_access_key(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  access_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:login.AccessKeyRsp.access_key)
}
void AccessKeyRsp::set_access_key(const void* value, size_t size) {
  
  access_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:login.AccessKeyRsp.access_key)
}
::std::string* AccessKeyRsp::mutable_access_key() {
  
  // @@protoc_insertion_point(field_mutable:login.AccessKeyRsp.access_key)
  return access_key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* AccessKeyRsp::release_access_key() {
  // @@protoc_insertion_point(field_release:login.AccessKeyRsp.access_key)
  
  return access_key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void AccessKeyRsp::set_allocated_access_key(::std::string* access_key) {
  if (access_key != NULL) {
    
  } else {
    
  }
  access_key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), access_key);
  // @@protoc_insertion_point(field_set_allocated:login.AccessKeyRsp.access_key)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace login

// @@protoc_insertion_point(global_scope)
