# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_format.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data_format.proto',
  package='data_format',
  syntax='proto3',
  serialized_pb=_b('\n\x11\x64\x61ta_format.proto\x12\x0b\x64\x61ta_format*L\n\nDataFormat\x12\t\n\x05\x42\x45GIN\x10\x00\x12\x0c\n\x08PROTOBUF\x10\x01\x12\x10\n\x0cPROTOBUF_ZIP\x10\x02\x12\x13\n\x0fPROTOBUF_SNAPPY\x10\x03\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_DATAFORMAT = _descriptor.EnumDescriptor(
  name='DataFormat',
  full_name='data_format.DataFormat',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BEGIN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROTOBUF', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROTOBUF_ZIP', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROTOBUF_SNAPPY', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=34,
  serialized_end=110,
)
_sym_db.RegisterEnumDescriptor(_DATAFORMAT)

DataFormat = enum_type_wrapper.EnumTypeWrapper(_DATAFORMAT)
BEGIN = 0
PROTOBUF = 1
PROTOBUF_ZIP = 2
PROTOBUF_SNAPPY = 3


DESCRIPTOR.enum_types_by_name['DataFormat'] = _DATAFORMAT


# @@protoc_insertion_point(module_scope)
